version: '1.0.{build}'

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

install:
    - git submodule update --init --recursive

before_build:
    - cmake -DBUILD_TESTS=True -DBUILD_EXAMPLES=True .

build:
    project: $(APPVEYOR_BUILD_FOLDER)\lsqcpp.sln

test_script:
    - '%APPVEYOR_BUILD_FOLDER%\test\Debug\run_tests.exe'
