intf_libs =
impl_libs =
import intf_libs += Eigen%lib{Eigen}

./: lib{least-squares-cpp}: lsqcpp/hxx{*} $intf_libs

lib{least-squares-cpp}:
{
    cxx.export.poptions = "-I$out_base" "-I$src_base"
    cxx.export.libs = $intf_libs
}

hxx{*}: install.subdirs = true
